services:
  jekyll:
    # image: jekyll/jekyll:latest
    image: starefossen/github-pages:latest # match github environment
    command: jekyll serve --drafts --unpublished --future --livereload --force_polling
    ports:
      - "4000:4000"
      - "35729:35729" # Required for Livereload
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
